### PR TITLE
fix: better ux for e-Invoice and e-Waybill applicability

### LINKED ISSUE #1577: better ux for e-Invoice and e-Waybill applicability
- Always show buttons
- Throw if not eligible with all errors
- Button can be greyed
- For Generate and Cancel Actions.

### PR DESCRIPTION
**Pull request by vishakhdesai**
Closes #1577

image
image
image
image
image

### CODE REVIEW

File: india_compliance/gst_india/client_scripts/e_waybill_actions.js [hunk 1]
```diff
@@ -33,13 +33,41 @@ function setup_e_waybill_actions(doctype) {
...
+                        show_e_waybill_applicability_status(
+                            frm,
+                            is_e_waybill_applicable(frm, true)
+                        ),
+                    "e-Waybill"
+                );
                 return;
+            }
+
+            if (frm.doc.docstatus == 1 && !is_e_waybill_applicable(frm, true)) {
```
Comment (vorasmit) [inline india_compliance/gst_india/client_scripts/e_waybill_actions.js]: - Wrapper function for show message
- Extend this to cover generatable messages
- refactor and better variable names
- Use Generatable API
- e-Waybill cannot be generated
