### PR TITLE
fix: sub supply type "Others" for e-waybill in DN

### LINKED ISSUE #2212: sub supply type "Others" for e-waybill in DN
- [x] Add option for sub-supply type others in DN, with sub supply desc
- [x] Readonly sub-supply type in all transactions

after: #2210

### PR DESCRIPTION
**Pull request by Sanket322**
closes: #2212

### Add more verbosity for default options

image_2024-07-24_16-23-05

<sub><a href="https://huly.app/guest/resilienttech?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NjlmYjQzYzdmMDllZGM1NjA2MTk5NzgiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6Inctc21pdHZvcmEyMDMtcmVzaWxpZW50dGVjLTY2N2U0MjkxLWEwNWMwNjY4N2EtNjM4MjY3IiwicHJvZHVjdElkIjoiIn0.1V6RSX8HVVfgbBuYfI9zT3ce3Wcg-fzo3F-omaV5P90">Huly&reg;: <b>IC-2581</b></a></sub>

### CODE REVIEW

File: india_compliance/gst_india/client_scripts/e_waybill_actions.js [hunk 1]
```diff
@@ -488,9 +514,9 @@ function get_sub_suppy_type_options(frm) {
 
         if (frm.doc.is_return) {
             if (same_gstin) {
-                options = ["For Own Use", "Exhibition or Fairs"];
+                options = ["For Own Use", "Exhibition or Fairs","Others"];
```
Comment (ljain112) [inline india_compliance/gst_india/client_scripts/e_waybill_actions.js]: This function can directly be used to get other supply type options

File: india_compliance/gst_india/client_scripts/e_waybill_actions.js [hunk 2]
```diff
@@ -444,6 +443,33 @@ function get_generate_e_waybill_dialog(opts, frm) {
...
+            "Purchase Receipt_0": { sub_supply_type: "Supply" },
+            "Purchase Receipt_1": { sub_supply_type: "Others" },
+        };
+
+        const key = `${frm.doctype}_${frm.doc.is_return}`;
+        const default_sub_supply_type = default_supply_types[key].sub_supply_type;
+
+        fields.splice(5, 0, {
+            label: "Sub Supply Type",
+            fieldname: "sub_supply_type",
```
Comment (ljain112) [inline india_compliance/gst_india/client_scripts/e_waybill_actions.js]: duplication
