### PR TITLE
fix(ui): show sandbox mode indicator in transaction doctypes

### LINKED ISSUE #1055: Sandbox Mode status for frontend in Transactions (like: Experimental)
### Suggested Implementation

Sidebar in Transactions

image_2023-07-28_15-49-29

### PR DESCRIPTION
**Pull request by DaizyModi**
image

### CODE REVIEW

File: india_compliance/public/js/transaction.js [hunk 1]
```diff
@@ -22,6 +23,31 @@ for (const doctype of ["Sales Invoice", "Delivery Note"]) {
     ignore_port_code_validation(doctype);
 }
 
+function show_sandbox_mode_indicator(doctype) {
```
Comment (vorasmit) [inline india_compliance/public/js/transaction.js]: Keeping this in e-Waybill Actions would restrict this to relevant doctypes.
