### PR TITLE
fix: update taxable value calculation using `transfer_qty`

### LINKED ISSUE #3641: Grand Total not updating on change of basic rate in Stock Entry.
Frappe Support Issue: https://support.frappe.io/app/hd-ticket/47357

### PR DESCRIPTION
**Pull request by karm1000**
Support Ticket: https://support.frappe.io/helpdesk/tickets/51112

## Summary by CodeRabbit

* **Bug Fixes**
  * Use transfer quantity for tax and amount calculations on Stock Entry and related receipt lines, yielding accurate taxable values.
  * Refresh item lines after recalculation so amount fields respect precision and updated taxable totals display immediately.

### CODE REVIEW

File: india_compliance/public/js/taxes_controller.js [hunk 1]
```diff
@@ -249,6 +252,14 @@ Object.assign(india_compliance.taxes_controller_events, {
         frm.taxes_controller.update_tax_amount();
     },
 
+    amount(frm, cdt, cdn) {
+        console.log("in amount");
```
Comment (ljain112) [inline india_compliance/public/js/taxes_controller.js]: .
