### PR TITLE
fix: Fix datetime format for last sync account details

### LINKED ISSUE #4015: UI: Inconsistent Date Time formatting On Account Page
Image

### PR DESCRIPTION
**Pull request by Abdeali099**
- closes: #4015 

## Before:

image_2026-02-23_14-00-16

## After:

image

> [!NOTE]
> Backport to V-16 and V-15

### CODE REVIEW

File: india_compliance/public/js/india_compliance_account/pages/AccountPage.vue [hunk 1]
```diff
@@ -167,13 +167,14 @@ data() {
   },
   computed: {
     last_synced_on() {
-      // TODO: set based on user datetime format?
       let { last_usage_synced_on } = this.subscriptionDetails;
-      last_usage_synced_on = last_usage_synced_on
-        ? moment.unix(last_usage_synced_on)
-        : moment();
+      if (!last_usage_synced_on) return "";
```
Comment (karm1000) [inline india_compliance/public/js/india_compliance_account/pages/AccountPage.vue:175]: Keep this. As somehow, if there is empty `last_usage_synced_on` now `date time` is shown.
Or it'll look like this.

Image

Comment (Abdeali099) [reply india_compliance/public/js/india_compliance_account/pages/AccountPage.vue:175]: Ohk

**Review by karm1000 — DISMISSED** [review]

**Comment by Abdeali099** [comment]
Test Case failed? Not related to this PR

**Comment by karm1000** [comment]
@mergify update

File: india_compliance/public/js/india_compliance_account/pages/AccountPage.vue [hunk 2]
```diff
@@ -167,13 +167,13 @@ data() {
...
-      // TODO: set based on user datetime format?
       let { last_usage_synced_on } = this.subscriptionDetails;
-      last_usage_synced_on = last_usage_synced_on
-        ? moment.unix(last_usage_synced_on)
-        : moment();
 
-      return last_usage_synced_on.format("DD-MM-YYYY HH:mm A");
+      const datetime = (
+        last_usage_synced_on ? moment.unix(last_usage_synced_on) : moment()
+      ).format(frappe.defaultDatetimeFormat);
```
[the remark this answers is not in the document]
Comment (Abdeali099) [reply india_compliance/public/js/india_compliance_account/pages/AccountPage.vue:174]: 0 not possible

**Comment by Abdeali099** [comment]
@karm1000 ready to merge

File: india_compliance/public/js/india_compliance_account/pages/AccountPage.vue [hunk 3]
```diff
@@ -27,7 +27,7 @@
             </div>
           </div>
           <router-link v-if="!is_unlimited_account"
-            class="btn btn-primary btn-sm btn-block"
+            class="btn btn-primary btn-lg"
```
Comment (karm1000) [inline india_compliance/public/js/india_compliance_account/pages/AccountPage.vue]: I think it is inconsistant to other button. WDYT?

Image

Comment (Abdeali099) [reply india_compliance/public/js/india_compliance_account/pages/AccountPage.vue]: I think this button also don't need to be length? WDYT?

Thanks for your attention!

**Review by karm1000 — APPROVED** [review]
