### PR TITLE
fix: e-waybill validations and enhancements

### LINKED ISSUE #1023: Unable to update E-way bill- "Update Vehicle Info" if want to change mode of transport
In ERP Next v14, update vehicle info option is available in Sales invoice>E-way bill. but if mode of transport is changed like road to train that update vehicle info form have missing some mandatory field like place of change, RR No. & Date. so without fill this information ERP is unable to update E-way bill.

**For ref. below is vehicle update form in ERP**
image

And below is actual vehicle update form in E-way bill portal.
image

So please fix the issue.

**version details**
Installed Apps
Ecommerce Integrations: v1.17.4 (HEAD)

ERPNext: v14.29.1 (HEAD)

erpnext_org_structure: v0.0.1 (HEAD)

Frappe Framework: v14.40.1 (HEAD)

Frappe HR: v14.5.0 (HEAD)

India Compliance: v14.10.4 (HEAD)

Payments: v0.0.1 (HEAD)

Rangsutra: v0.0.1 (HEAD)

Rangsutra Custom Reports: v0.0.1 (HEAD)

Regards
**Sunil**

### PR DESCRIPTION
**Pull request by vorasmit**
- [x] Check for debit_note or is_return only for autogeneration
- [x] e-Waybill for Purchase Invoice -- Address Check
- [x] e-Waybill applicability should not check for address
- [ ] e-Waybill in Purchase Receipt

### CODE REVIEW

**Comment by ljain112** [comment]
Closes: #1023

File: india_compliance/gst_india/client_scripts/sales_invoice.js [hunk 1]
```diff
@@ -51,6 +71,14 @@ async function gst_invoice_warning(frm) {
     }
 }
 
+function set_e_invoice_status_options(frm) {
```
Comment (vorasmit) [inline india_compliance/gst_india/client_scripts/sales_invoice.js]: function name?

File: india_compliance/gst_india/client_scripts/sales_invoice.js [hunk 2]
```diff
@@ -34,8 +34,28 @@ frappe.ui.form.on(DOCTYPE, {
...
+            frm.doc.is_return ||
+            frm.doc.is_debit_note ||
+            !has_e_waybill_threshold_met(frm) ||
+            !is_e_waybill_applicable(frm)
+        )
+            return;
+
+        frappe.show_alert(
+            {
+                message: __("Supplier Address is required to create e-Waybill"),
```
Comment (vorasmit) [inline india_compliance/gst_india/client_scripts/sales_invoice.js]: Error Message?

File: india_compliance/gst_india/client_scripts/purchase_invoice.js [hunk 3]
```diff
@@ -9,9 +9,11 @@ frappe.ui.form.on(DOCTYPE, {
 
     after_save(frm) {
         if (
-            frm.doc.docstatus ||
             frm.doc.supplier_address ||
-            !is_e_waybill_applicable(frm)
+            !frm.doc.gst_category === "Unregistered" ||
```
Comment (vorasmit) [inline india_compliance/gst_india/client_scripts/purchase_invoice.js]: use !==
Not logical. Should always check for applicability and threshold if unregistered or is_return. Check similarly in Sales Invoice

File: india_compliance/gst_india/client_scripts/delivery_note.js [hunk 4]
```diff
@@ -9,15 +9,18 @@ frappe.ui.form.on(DOCTYPE, {
 
     after_save(frm) {
         if (
-            frm.doc.docstatus ||
             frm.doc.customer_address ||
-            !(gst_settings.enable_e_waybill && gst_settings.enable_e_waybill_from_dn)
+            !has_e_waybill_threshold_met(frm) ||
```
Comment (vorasmit) [inline india_compliance/gst_india/client_scripts/delivery_note.js]: A threshold check is not applicable for subcontracting.

File: india_compliance/gst_india/client_scripts/e_waybill_actions.js [hunk 5]
```diff
@@ -1149,6 +1167,18 @@ function get_destination_address_name(frm) {
     }
 }
 
+function get_dispatch_address_name(frm) {
+    if (frm.doc.doctype == "Purchase Invoice") {
```
Comment (vorasmit) [inline india_compliance/gst_india/client_scripts/e_waybill_actions.js]: Port Address? Make sure it's similar to backend logic. Can we use the backend function here instead of replicating it here? Already we are using get_doc

File: india_compliance/gst_india/client_scripts/e_waybill_applicability.js [hunk 6]
```diff
@@ -0,0 +1,87 @@
...
+                !item.gst_hsn_code.startsWith("99") &&
+                item.qty !== 0
+            )
+                return true;
+        }
+
+        return false;
+    }
+    is_e_waybill_generatable_using_api() {
+        return this.is_e_waybill_applicable && india_compliance.is_api_enabled();
```
Comment (vorasmit) [inline india_compliance/gst_india/client_scripts/e_waybill_applicability.js]: function call

File: india_compliance/gst_india/client_scripts/e_waybill_applicability.js [hunk 7]
```diff
@@ -0,0 +1,87 @@
...
+        return false;
+    }
+}
+
+class SalesInvoiceEwaybill extends EwaybillApplicability {
+    is_e_waybill_generatable_using_api() {
+        return (
+            super.is_e_waybill_generatable_using_api() &&
+            this.frm.doc.company_gstin !== this.frm.doc.customer_gstin &&
+            this.frm.doc.customer_address
```
Comment (vorasmit) [inline india_compliance/gst_india/client_scripts/e_waybill_applicability.js]: With this, the Generate button will not be visible. Instead, it should throw while trying to generate. It would confuse users if button is not visible.

File: india_compliance/gst_india/client_scripts/purchase_invoice.js [hunk 8]
```diff
@@ -3,15 +3,17 @@ setup_e_waybill_actions(DOCTYPE);
...
         show_sandbox_mode_indicator();
     },
 
     after_save(frm) {
         if (
-            frm.doc.docstatus ||
             frm.doc.supplier_address ||
-            !is_e_waybill_applicable(frm)
+            frm.doc.gst_category !== "Unregistered" ||
+            !frm.doc.is_return ||
```
Comment (vorasmit) [inline india_compliance/gst_india/client_scripts/purchase_invoice.js]: ..

File: india_compliance/gst_india/client_scripts/e_waybill_actions.js [hunk 9]
```diff
@@ -226,28 +229,44 @@ function show_generate_e_waybill_dialog(frm) {
...
 
     d.show();
 
+    //Alert if E-waybill cannot be generated using api
+    if (api_enabled && !is_e_waybill_generatable_using_api(frm)) {
+        let address = frm.doc.customer_address || frm.doc.supplier_address;
+        let reason = !address ? "address is missing." : "of same GSTIN billing.";
+        $(`
+            <div class="alert alert-warning" role="alert">
+                e-Waybill cannot be generated using API because ${reason}
```
Comment (vorasmit) [inline india_compliance/gst_india/client_scripts/e_waybill_actions.js]: error message.

File: india_compliance/gst_india/client_scripts/e_waybill_applicability.js [hunk 10]
```diff
@@ -0,0 +1,87 @@
...
+
+    auto_generate_e_waybill() {
+        if (
+            this.frm.doc.is_return ||
+            this.frm.doc.is_debit_note ||
+            this.frm.doc.ewaybill ||
+            !gst_settings.auto_generate_e_waybill ||
+            !this.is_e_waybill_generatable_using_api() ||
+            !has_e_waybill_threshold_met() ||
+            !is_e_invoice_applicable(frm)
```
Comment (vorasmit) [inline india_compliance/gst_india/client_scripts/e_waybill_applicability.js]: .

File: india_compliance/gst_india/client_scripts/delivery_note.js [hunk 11]
```diff
@@ -3,21 +3,19 @@ setup_e_waybill_actions(DOCTYPE);
...
     },
 
     after_save(frm) {
-        if (
-            frm.doc.docstatus ||
-            frm.doc.customer_address ||
-            !(gst_settings.enable_e_waybill && gst_settings.enable_e_waybill_from_dn)
-        )
-            return;
+        if (!is_e_waybill_generatable(frm)) return;
```
Comment (vorasmit) [inline india_compliance/gst_india/client_scripts/delivery_note.js]: check for applicability.
