### PR TITLE
fix: validate invoice no for e-waybill and e-invoice

### LINKED ISSUE #1350: Validate gst invoice number for all the transction doctype where api is callable
Frappe Support : https://support.frappe.io/app/hd-ticket/6243

### PR DESCRIPTION
**Pull request by ljain112**
closes: #1350

### CODE REVIEW

File: india_compliance/gst_india/client_scripts/document_naming_settings.js [hunk 1]
```diff
@@ -0,0 +1,24 @@
...
+
+    frm.dashboard.set_headline_alert(
+        `GST Invoice Number cannot exceed 14 characters and
+            should start with an alphanumeric character.
+            It can only contain alphanumeric characters, dash (-) and slash (/).`,
+        "blue"
+    );
+}
+
+function show_gst_gst_invoice_no_banner(transaction_type) {
```
Comment (vorasmit) [inline india_compliance/gst_india/client_scripts/document_naming_settings.js]: purchase receipt.
is_invoice_no_validation_required

throw on the generate button
even in the naming rule.
