### PR TITLE
fix: Scope DOM manipulation to current doctype

### LINKED ISSUE #2611: UI: Purchase Reco Tool and Beta
Steps to reproduce:
Open GSTR-1, Open Purchase Reco, Reconcile, Open GSTR-1

image

### PR DESCRIPTION
**Pull request by Sanket322**
- closes: #2611

### CODE REVIEW

File: india_compliance/gst_india/doctype/purchase_reconciliation_tool/purchase_reconciliation_tool.js [hunk 1]
```diff
@@ -132,10 +132,10 @@ frappe.ui.form.on("Purchase Reconciliation Tool", {
         );
 
         // move actions button next to filters
-        for (let button of $(".custom-actions .inner-group-button")) {
+        for (let button of frm.$wrapper.find(".custom-actions .inner-group-button")) {
             if (button.innerText?.trim() != "Actions") continue;
-            $(".custom-button-group .inner-group-button").remove();
-            $(button).appendTo($(".custom-button-group"));
+            frm.$wrapper.find(".custom-button-group .inner-group-button").remove();
```
Comment (vorasmit) [inline india_compliance/gst_india/doctype/purchase_reconciliation_tool/purchase_reconciliation_tool.js]: completeness check
