### PR TITLE
fix: update state name to `Puducherry`

### LINKED ISSUE #541: State Name as `Puducherry` is received from GSTIN Search API

### PR DESCRIPTION
**Pull request by sagarvora**
Closes https://github.com/resilient-tech/india-compliance/issues/541

### CODE REVIEW

File: india_compliance/public/js/india_compliance_account/pages/PaymentPage.vue [hunk 1]
```diff
@@ -136,45 +136,7 @@ export default {
...
-        "Rajasthan",
-        "Sikkim",
-        "Tamil Nadu",
-        "Telangana",
-        "Tripura",
-        "Uttar Pradesh",
-        "Uttarakhand",
-        "West Bengal",
-      ]
+      const states = frappe.boot.india_state_options || [];
```
Comment (sagarvora) [inline india_compliance/public/js/india_compliance_account/pages/PaymentPage.vue:139]: tested.

File: india_compliance/patches/post_install/update_state_name_to_puducherry.py [hunk 2]
```diff
@@ -0,0 +1,12 @@
+import frappe
+
+
+def execute():
+    frappe.db.set_value(
+        "Address",
+        {"gst_state": "Pondicherry"},
+        {
+            "gst_state": "Puducherry",
+            "state": "Puducherry",
```
Comment (sagarvora) [inline india_compliance/patches/post_install/update_state_name_to_puducherry.py:10]: @vorasmit I am updating the `state` field as well, but I can undo that if needed.
