### PR TITLE
fix: set party type from pan no

### LINKED ISSUE #2052: Can customer type/supplier type can be set based on GST Search API ?
https://support.frappe.io/app/hd-ticket/13606

### PR DESCRIPTION
**Pull request by Sanket322**
Closes : #2052

### CODE REVIEW

**Comment by vorasmit** [comment]
We can patch party type proprietorship in ERPNext. Use Individual instead.
@ljain112 Thoughts?

File: india_compliance/gst_india/client_scripts/party.js [hunk 1]
```diff
@@ -70,6 +70,9 @@ function validate_gstin(doctype) {
             if (PAN_REGEX.test(pan)) {
                 frm.doc.pan = pan;
                 frm.refresh_field("pan");
+                if(["Customer", "Supplier"].includes(doctype)){
```
Comment (vorasmit) [inline india_compliance/gst_india/client_scripts/party.js]: Can be common condition for `set_party_type`. You can access doctype as `frm.doc.doctype`
