### PR TITLE
fix: allow taxable items with non-taxable items

### LINKED ISSUE #1454: Remove restrictions placed currently on Non-GST items -> Required as a part of separate invoice currently

### PR DESCRIPTION
**Pull request by ljain112**
Closes: #1454 
- Allow Taxable Items with Non-Taxable Items(nil-rated,exempted,non-gst) Items.
- Allow e-waybill for Non-GST Items

image

### CODE REVIEW

File: india_compliance/gst_india/client_scripts/e_waybill_applicability.js [hunk 1]
```diff
@@ -52,6 +52,7 @@ class SalesInvoiceEwaybill extends EwaybillApplicability {
             !gst_settings.auto_generate_e_waybill ||
             !this.is_e_waybill_generatable() ||
             !has_e_waybill_threshold_met(this.frm) ||
+            frm.doc.items.every(item => item.gst_treatment == "Non-GST") ||
```
Comment (vorasmit) [inline india_compliance/gst_india/client_scripts/e_waybill_applicability.js]: .

File: india_compliance/gst_india/doctype/gst_settings/gst_settings.json [hunk 2]
```diff
@@ -379,12 +380,18 @@
    "fieldname": "enable_e_waybill_from_pr",
    "fieldtype": "Check",
    "label": "Enable e-Waybill Generation from Purchase Receipt"
+  },
+  {
```
Comment (vorasmit) [inline india_compliance/gst_india/doctype/gst_settings/gst_settings.json]: .

File: india_compliance/gst_india/overrides/purchase_invoice.py [hunk 3]
```diff
@@ -65,7 +65,7 @@ def is_b2b_invoice(doc):
         or doc.gst_category in ["Registered Composition", "Unregistered", "Overseas"]
         or doc.supplier_gstin == doc.company_gstin
         or doc.is_opening == "Yes"
-        or any(row for row in doc.items if row.gst_treatment == "Non-GST")
+        or all(row for row in doc.items if row.gst_treatment == "Non-GST")
```
Comment (vorasmit) [inline india_compliance/gst_india/overrides/purchase_invoice.py]: any taxable

File: india_compliance/gst_india/overrides/sales_invoice.py [hunk 4]
```diff
@@ -173,6 +173,7 @@ def on_submit(doc, method=None):
         and is_e_waybill_applicable(doc, gst_settings)
         and not doc.is_debit_note
         and not doc.is_return
+        and not all(row for row in doc.items if row.gst_treatment == "Non-GST")
```
Comment (vorasmit) [inline india_compliance/gst_india/overrides/sales_invoice.py]: not req

File: india_compliance/gst_india/overrides/transaction.py [hunk 5]
```diff
@@ -422,20 +422,6 @@ def _throw(message, title=None):
     return all_valid_accounts
 
 
-def validate_tax_accounts_for_non_gst(doc):
```
Comment (vorasmit) [inline india_compliance/gst_india/overrides/transaction.py:425]: at the time of setting GST details,
check => Non-GST with Tax Rate/Amount Throw.
try except in get method for patch

File: india_compliance/gst_india/overrides/transaction.py [hunk 6]
```diff
@@ -463,13 +449,14 @@ def validate_items(doc):
...
 
-    if not has_gst_items:
-        update_taxable_values(doc, [])
-        validate_tax_accounts_for_non_gst(doc)
-
-        return False
-
-    if non_gst_items:
+    if (
+        non_gst_items
```
Comment (vorasmit) [inline india_compliance/gst_india/overrides/transaction.py]: Check validations if all items are non_gst / non_taxable
