### PR TITLE
fix: mark e-invoice log as cancelled, useful after deletion of IRN from GSTR-1

### LINKED ISSUE #1039: Mark e-invoice as deleted from GSTR-1
On this, the following statistics can improve.
image

### PR DESCRIPTION
**Pull request by DaizyModi**
**e-Invoice Log**
image

Closes: #1039

### CODE REVIEW

File: india_compliance/gst_india/client_scripts/e_invoice_actions.js [hunk 1]
```diff
@@ -3,6 +3,18 @@ frappe.ui.form.on("Sales Invoice", {
...
 
+        if (
+            frm.doc.irn &&
+            frm.doc.docstatus == 2 &&
+            frappe.perm.has_perm(frm.doctype, 0, "cancel", frm.doc.name)
+        ) {
+            frm.add_custom_button(
+                __("Mark as Cancelled"),
+                () => show_mark_e_invoice_as_cancelled_dialog(frm),
+                "e-Invoice Log"
```
Comment (vorasmit) [inline india_compliance/gst_india/client_scripts/e_invoice_actions.js]: Just `e-Invoice` should be sufficient
