### PR TITLE
fix: handle `Actions` button for smaller screens

### LINKED ISSUE #2595: Purchase Reco: Action button in small screen
- [x] Hide `Actions` next to filter, because it is available on page's action menu 

<sub><a href="https://huly.app/guest/resilienttech?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NmQ5OWMzZTNiYjU3YTg1ZTg1NzkzOTkiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6Inctc21pdHZvcmEyMDMtcmVzaWxpZW50dGVjLTY2N2U0MjkxLWEwNWMwNjY4N2EtNjM4MjY3In0.CG3hUEPxly-IPm9Bq1w9fqD7DndyVvbcniTCe_k5m_w">Huly&reg;: <b>IC-2714</b></a></sub>

### PR DESCRIPTION
**Pull request by Abdeali099**
- closes: #2595

**Before:**

before-actions

**After:**

after-action-2

<sub><a href="https://huly.app/guest/resilienttech?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzRjMGU5OGQyZWY0Y2JjYzQ2Y2ZjMTIiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6Inctc21pdHZvcmEyMDMtcmVzaWxpZW50dGVjLTY2N2U0MjkxLWEwNWMwNjY4N2EtNjM4MjY3In0.D2lYpIgDEfGqanbZoqwmxt0av-3XburJyZqeP167HHk">Huly&reg;: <b>IC-2932</b></a></sub>

### CODE REVIEW

File: india_compliance/gst_india/doctype/purchase_reconciliation_tool/purchase_reconciliation_tool.js [hunk 1]
```diff
@@ -133,8 +135,17 @@ frappe.ui.form.on("Purchase Reconciliation Tool", {
...
-            if (button.innerText?.trim() != "Actions") continue;
+            if (button.innerText?.trim() != action_group) continue;
             $(".custom-button-group .inner-group-button").remove();
+
+            // to hide `Actions` text on small screens
+            $(button)
+                .find("button")
+                .html(
+                    `<span class="button-label hidden-xs">${action_group}</span>
+                    ${frappe.utils.icon("select")}`
```
Comment (vorasmit) [inline india_compliance/gst_india/doctype/purchase_reconciliation_tool/purchase_reconciliation_tool.js]: three dots horizontal.

**Comment by vorasmit** [comment]
UI compatibility for backport?

**Comment by Abdeali099** [comment]
> UI compatibility for backport?

UI is compatible, but require manual backport
