### PR TITLE
fix: GST Transporter ID Refactor

### LINKED ISSUE #2072: Inconsistency with GST Transporter ID
Frappe Support Issue: https://support.frappe.io/app/hd-ticket/13855
image

Eg Transporter ID: 29AAFCA7488L1Z0
This is a valid transporter ID but Invalid GSTIN and check digit validation is failing.

### Proposed Solution 
- Avoid check digit validation for all transporter ID and only validate GSTIN regex
- Use directly transporter ID API for all the gstin with transporter or Remove transporter validation at all.

### PR DESCRIPTION
**Pull request by vishakhdesai**

### CODE REVIEW

File: india_compliance/gst_india/client_scripts/supplier.js [hunk 1]
```diff
@@ -30,6 +30,6 @@ frappe.ui.form.on(DOCTYPE, {
             return;
 
         gst_transporter_id_field = frm.get_field("gst_transporter_id");
-        india_compliance.set_gstin_status(gst_transporter_id_field);
+        india_compliance.validate_gst_transporter_id(gst_transporter_id_field.value);
```
Comment (ljain112) [inline india_compliance/gst_india/client_scripts/supplier.js]: .

File: india_compliance/gst_india/doctype/gstin/gstin.json [hunk 2]
```diff
@@ -59,12 +59,19 @@
    "in_list_view": 1,
    "in_standard_filter": 1,
    "label": "Is Blocked"
+  },
+  {
+   "fieldname": "transporter_id_status",
+   "fieldtype": "Data",
```
Comment (vorasmit) [inline india_compliance/gst_india/doctype/gstin/gstin.json:67]: perms, in list view, in standard filter
