### PR TITLE
fix: add duplicate GSTIN and PAN message checks in party and address

### LINKED ISSUE #3781: Show alert if user is creating different party with same GSTIN.

### PR DESCRIPTION
**Pull request by ljain112**
closes: https://github.com/resilient-tech/india-compliance/issues/3781

image

image

## Summary by CodeRabbit

* **New Features**
  * Duplicate-detection for GSTIN and PAN across parties and linked addresses; surfaces orange alerts when potential conflicts are found.
  * Duplicate checks trigger automatically after GSTIN/PAN entry and during quick-entry flows for faster review.
  * Alerts include contextual, highlighted links to matching records (including via-address matches) to aid resolution.

<sub>✏️ Tip: You can customize this high-level summary in your review settings.</sub>

### CODE REVIEW

**Comment by karm1000** [comment]
@ljain112 Also add this validation in `quick entry form`

File: india_compliance/gst_india/client_scripts/party.js [hunk 1]
```diff
@@ -79,6 +80,35 @@ function validate_gstin(doctype) {
...
+    if (!doc.gstin) return;
+
+    let args = {
+        gstin: doc.gstin,
+        party_type: doc.doctype,
+        party: doc.name,
+    };
+
+    if (doc.doctype === "Address") {
+        if (!doc.links || doc.links.length !== 1) return;
```
Comment (karm1000) [inline india_compliance/gst_india/client_scripts/party.js]: Why this check?

File: india_compliance/gst_india/utils/__init__.py [hunk 2]
```diff
@@ -1131,3 +1132,121 @@ def has_permission_of_page(page_name, throw=False):
...
+
+def _show_duplicate_alert(field_label, value, party_type, duplicate_links):
+    msg = _("{0} {1} is already registered with the following {2}(s):").format(
+        field_label,
+        frappe.bold(value),
+        party_type,
+    )
+    msg += f"<br><br><ul>{''.join(duplicate_links)}</ul>"
+
+    frappe.msgprint(msg=msg, indicator="orange")
```
Comment (karm1000) [inline india_compliance/gst_india/utils/__init__.py]:
```suggestion
    frappe.msgprint(msg=msg, indicator="blue")
```

File: india_compliance/gst_india/client_scripts/party.js [hunk 3]
```diff
@@ -79,6 +80,35 @@ function validate_gstin(doctype) {
     });
 }
 
+function check_duplicate_gstin(doc) {
+    if (!doc.gstin) return;
+
+    let args = {
+        gstin: doc.gstin,
+        party_type: doc.doctype,
+        party: doc.name,
```
Comment (karm1000) [inline india_compliance/gst_india/client_scripts/party.js]: For new document, name is just a temporary name. So make `party` an optional argument.

File: india_compliance/gst_india/utils/__init__.py [hunk 4]
```diff
@@ -1131,3 +1132,121 @@ def has_permission_of_page(page_name, throw=False):
...
+    """
+    return frappe.get_all(
+        party_type,
+        filters={"pan": ("=", pan), "name": ("!=", party)},
+        pluck="name",
+    )
+
+
+@frappe.whitelist()
+def check_duplicate_gstin(gstin, party_type, party, address_name=None):
```
Comment (karm1000) [inline india_compliance/gst_india/utils/__init__.py]: `party` as optional parameter

File: india_compliance/gst_india/client_scripts/party.js [hunk 5]
```diff
@@ -88,12 +118,30 @@ function validate_pan(doctype) {
...
     });
 }
 
+function check_duplicate_pan(doc) {
+    if (!doc.pan) return;
+
+    let args = {
+        pan: doc.pan,
+        party_type: doc.doctype,
+        party: doc.name,
```
Comment (karm1000) [inline india_compliance/gst_india/client_scripts/party.js]: For new document, name is just a temporary name. So make `party` an optional argument.

File: india_compliance/gst_india/utils/__init__.py [hunk 6]
```diff
@@ -1131,3 +1132,121 @@ def has_permission_of_page(page_name, throw=False):
...
+def validate_party_type(party_type, party):
+    if party_type not in GST_PARTY_TYPES:
+        return
+
+    frappe.has_permission(party_type, doc=party, throw=True)
+    return True
+
+
+@frappe.whitelist()
+def check_duplicate_pan(pan, party_type, party):
```
Comment (karm1000) [inline india_compliance/gst_india/utils/__init__.py]: `party` as optional parameter

File: india_compliance/gst_india/client_scripts/party.js (hunk 1 above)
Comment (ljain112) [reply india_compliance/gst_india/client_scripts/party.js]: What if the user has linked multiple parties?

File: india_compliance/gst_india/utils/__init__.py (hunk 2 above)
Comment (ljain112) [reply india_compliance/gst_india/utils/__init__.py]: not required

File: india_compliance/public/js/quick_entry.js [hunk 7]
```diff
@@ -97,10 +97,13 @@ class GSTQuickEntryForm extends frappe.ui.form.QuickEntryForm {
                 onchange: () => {
                     const d = this.dialog;
 
+                    check_duplicate_gstin(d, this.doctype);
```
Comment (vorasmit) [inline india_compliance/public/js/quick_entry.js]: ux: this will create duplicate records with alert. better ux would be where user confirms if it's okay to create a duplicate record.

**Comment by karm1000** [comment]
LGTM

File: india_compliance/public/js/quick_entry.js [hunk 8]
```diff
@@ -493,3 +498,29 @@ function get_gstin_description() {
 
     return __("Autofill is not supported in sandbox mode");
 }
+
+function check_duplicate_gstin(dialog, doctype) {
```
Comment (vorasmit) [inline india_compliance/public/js/quick_entry.js]: common utility

File: india_compliance/gst_india/client_scripts/party.js [hunk 9]
```diff
@@ -79,6 +80,35 @@ function validate_gstin(doctype) {
     });
 }
 
+function check_duplicate_gstin(doc) {
+    if (!doc.gstin) return;
+
+    let args = {
+        gstin: doc.gstin,
+        party_type: doc.doctype,
+        party: doc.__islocal ? null : doc.name,
```
Comment (vorasmit) [inline india_compliance/gst_india/client_scripts/party.js]: __islocal not reqd

File: india_compliance/gst_india/client_scripts/party.js [hunk 10]
```diff
@@ -79,6 +80,35 @@ function validate_gstin(doctype) {
...
+    };
+
+    if (doc.doctype === "Address") {
+        if (!doc.links || doc.links.length !== 1) return;
```
Comment (vorasmit) [inline india_compliance/gst_india/client_scripts/party.js]: duplicate party check not needed on address creation or updating.

**Review by vorasmit — APPROVED** [review]

**Comment by ljain112** [comment]
@mergifyio backport version-16-hotfix
